---
title: "taipeilifetable"
author: "Chen Ning Kuan"
date: "2019年3月7日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 讀資料 }
setwd("~/GitHub/master/data/taipei")
library(readxl)
require(survival)
library(plyr)
require(dplyr)
require(data.table)
library(readxl)


taipei102 <- read_excel("~/GitHub/master/data/taipei/taipei102.xls",col_names = FALSE)

taipei107 <- read_excel("~/GitHub/master/data/taipei/taipei107.xls",col_names = FALSE)

X<-taipei107[-c(1,2,3),]
colnames(X) <- c(X[1,] )
X <- X[-1,-c(seq(5,23,2))]
Y <- X[,-c(1,2,3)]
Z <- cbind(Y,X[,c(1,2)])
Y <- apply(Y,2,as.numeric)


```

```{r }
#datagenerator 此函數用來製造可用資料

datagenerator=function(X){
X<-X[-c(1,2,3),]
colnames(X) <- c(X[1,] )
X <- X[-1,-c(seq(5,23,2))]
Y <- X[,-c(1,2,3)]
Z <- cbind(Y,X[,c(1,2)])
Y <- apply(Y,2,as.numeric)
return(Y)
}

datagenerator1=function(X){
X<-X[-c(1,2,3),]
colnames(X) <- c(X[1,] )
X <- X[-1,-c(seq(5,23,2))]
Y <- X[,-c(2,3)]
Z <- cbind(Y,X[,c(1,2)])
return(X)
}


taipei102new<-datagenerator(taipei102)

taipei107new<-datagenerator(taipei107)

taipeilist <- list(  taipei102new,taipei107new )
dim(taipei102new)[1]
dim(taipei102new)[2]


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
AA <- matrix(unlist(taipeilist[1]),nrow=12) #構想

apply(matrix(unlist(taipeilist[1]),nrow=12),2,sum) #check
apply( taipei102new,2,sum) #check
 
Q <- unlist(taipeilist) %>%array(dim=c(12,10,10)) #另類絲路 以後或許可用
matrixuse=matrix(nrow=2,ncol=10)
for(i in 1:2){
  
  matrixuse[i,]<- apply(matrix(unlist(taipeilist[i]),nrow=12) ,2,sum)
  
} 
namecol <- colnames(taipei102new)
namerow <- c(102,107)
datause <- data.frame(matrixuse)

colnames(datause) <- namecol
rownames(datause) <- namerow

```
開始造nonparematric method

```{r   }
datause[,2]=datause[,1]+datause[,2]

datause <- datause[,-1] #合併小於一歲的人

conditionalsurvival=function(x){

  ans <- matrix(nrow=3,ncol=5)
  for(i in 1:4){
    
       ans[1,i] <- (x[1,i]-x[2,i+1])/x[1,i]
       ans[2,i] <- (x[1,i]-x[2,i+1])
       ans[3,i] <- x[1,i]
  }
  ans[1,5] <- (sum( x[1,5:9])-sum( x[2,6:9]))/sum(x[1,5:9])
  ans[2,5] <- (sum( x[1,5:9])-sum( x[2,6:9]))
  ans[3,5] <- sum(x[1,5:9])

  
  
  
  return(ans)
}

cond_hazard <- conditionalsurvival(datause)

cond_hazard[1:3,3] <- 0

cond_hazard



```



```{r}
st_hat <- function(x,t){
  
  ans <- sum(x>t)/length(x)
  
  return(ans)
  }


st_hat_total=function(x){ #想問同學 ㄧ有沒有更有效率的寫法 類似list comprehension
  
ans <-numeric(length(x))
  
  for(i in 1:length(x)){
    
    ans[i]<- st_hat(x,x[i])
  
  
  }
return(ans)
}
```

```{r}
xx <- c( 7.5  ,12.5,17.5,22.5  ,37.5    )

m <- cond_hazard[2,]

runif(m[1],min=5,max=10 )
runif(m[2],min=10,max=15 )
runif(m[3],min=15,max=20 )
runif(m[4],min=20,max=25 )
runif(m[5],min=25,max=50 )
data <- c( runif(m[1],min=5,max=10 ),
runif(m[2],min=10,max=15 ),
runif(m[4],min=20,max=25 ),
runif(m[5],min=25,max=50 ) )
sort(c(5,6,7,1,3))
data <- sort(data)
length(data)

```


```{r}

x <- data


y <- st_hat_total(data)

length(y)
plot(x,y,type="n") 
segments(x[-length(x)],y[-length(x)],x[-1],y[-length(x)]) 
points(x[-length(x)],y[-length(x)],pch=16) 
points(x[-1],y[-length(x)],pch=1) 
plot(x,y,type="s") 
st_hat_total(m)
```

